version: '2.4'
services:
  db1-com:
    container_name: db1-com
    image: harbor.bbotte.com/devops/mysql-server:0.035
    volumes:
      - /tmp/1:/var/lib/mysql
    ports:
      - 3316:3306
    networks:
      iris:
        ipv4_address: 172.17.1.10
    environment:
      MYSQL_ROOT_PASSWORD: "bbotte.com"
      MYSQL_INNODB_BUFFER_POOL_SIZE: "128M"
      DATADIR: "/var/lib/mysql"

  db2-com:
    container_name: db2-com
    image: harbor.bbotte.com/devops/mysql-server:0.035
    volumes:
      - /tmp/2:/var/lib/mysql
    ports:
      - 3326:3306
    networks:
      iris:
        ipv4_address: 172.17.1.20
    environment:
      MYSQL_ROOT_PASSWORD: "bbotte.com"
      MYSQL_INNODB_THREAD_CONCURRENCY: 2
      MYSQL_INNODB_BUFFER_POOL_SIZE: "128M"
      DATADIR: "/var/lib/mysql"
      MYSQL_SERVER_ID: 2   # db2-com is a slave mysql


networks:
  iris:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.17.1.0/24
